# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    paths:
      - '**.vue'
      - '!**.test.ts'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.mscz'
      - '**.conf'
      - '**.go'
      - 'Dockerfile'
      - '.Dockerignore'
      - '**/build-vue.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vue
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages
      run: npm ci
    - name: build
      run: npx vue-cli-service build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.node-version == '16.x' }}
      with:
        name: dist-node-${{ matrix.node-version }}
        path: |
          dist