# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ESLint

on:
  push:
    paths:
      - '**.vue'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '.eslintrc'
      - '.editorconfig'
      - '**/lint.yml'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install packages
      run: npm ci
    - name: Lint
      run: npx vue-cli-service lint --no-fix
#    - name: Strict lint
#      run: npx vue-cli-service lint --no-fix --max-warnings 0
#      continue-on-error: true
#      if: ${{ github.ref == 'refs/heads/main' }}